INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('andres', 'Guzman', 'profesor1@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('jhon', 'Guzman', 'profesor2@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('linus', 'Guzman', 'profesor3@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('erich', 'Guzman', 'profesor4@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('ralph', 'Guzman', 'profesor5@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('james', 'Guzman', 'profesor6@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('tornado', 'Guzman', 'profesor7@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('jade', 'Guzman', 'profesor8@gmail.com', '2023-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES ('doe', 'Guzman', 'profesor9@gmail.com', '2023-01-01');